### ISSUE TITLE
CUDA path not updated when compiling sh compile_op_pt.sh

### ISSUE THREAD

**Issue by binbbaz** [itailang/geometric_adv#2]
I have updated the necessary cuda paths in the recommended files.
I am using cuda-11.1. When I run **sh compile_op_pt.sh**, the CUDA paths in the **build.ninja** gets restored back to cuda-10.1 path everytime I compile it.

i have updated the cuda paths several times but it changes back to cuda-10.1 after running **sh compile_op_pt.sh**
Please find the errors below

sh compile_op_pt.sh
running install
running bdist_egg
running egg_info
writing chamfer_3D.egg-info/PKG-INFO
writing dependency_links to chamfer_3D.egg-info/dependency_links.txt
writing top-level names to chamfer_3D.egg-info/top_level.txt
reading manifest file 'chamfer_3D.egg-info/SOURCES.txt'
writing manifest file 'chamfer_3D.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'chamfer_3D' extension
Emitting ninja build file /home/20020006/geometric_adv/transfer/atlasnet/build/temp.linux-x86_64-3.6/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] /usr/local/cuda-10.1/bin/nvcc -I/home/20020006/.conda/envs/geo_adv/lib/python3.6/site-packages/torch/include -I/home/20020006/.conda/envs/geo_adv/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/20020006/.conda/envs/geo_adv/lib/python3.6/site-packages/torch/include/TH -I/home/20020006/.conda/envs/geo_adv/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-10.1/include -I/home/20020006/.conda/envs/geo_adv/include/python3.6m -c -c /home/20020006/geometric_adv/transfer/atlasnet/auxiliary/ChamferDistancePytorch/chamfer3D/chamfer3D.cu -o /home/20020006/geometric_adv/transfer/atlasnet/build/temp.linux-x86_64-3.6/auxiliary/ChamferDistancePytorch/chamfer3D/chamfer3D.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=chamfer_3D -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
FAILED: /home/20020006/geometric_adv/transfer/atlasnet/build/temp.linux-x86_64-3.6/auxiliary/ChamferDistancePytorch/chamfer3D/chamfer3D.o 
/usr/local/cuda-10.1/bin/nvcc -I/home/20020006/.conda/envs/geo_adv/lib/python3.6/site-packages/torch/include -I/home/20020006/.conda/envs/geo_adv/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/20020006/.conda/envs/geo_adv/lib/python3.6/site-packages/torch/include/TH -I/home/20020006/.conda/envs/geo_adv/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-10.1/include -I/home/20020006/.conda/envs/geo_adv/include/python3.6m -c -c /home/20020006/geometric_adv/transfer/atlasnet/auxiliary/ChamferDistancePytorch/chamfer3D/chamfer3D.cu -o /home/20020006/geometric_adv/transfer/atlasnet/build/temp.linux-x86_64-3.6/auxiliary/ChamferDistancePytorch/chamfer3D/chamfer3D.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=chamfer_3D -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
/bin/sh: 1: /usr/local/cuda-10.1/bin/nvcc: not found
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/20020006/.conda/envs/geo_adv/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1515, in _run_ninja_build
    env=env)
  File "/home/20020006/.conda/envs/geo_adv/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "auxiliary/ChamferDistancePytorch/chamfer3D/setup.py", line 13, in <module>
    'build_ext': BuildExtension
  File "/home/20020006/.conda/envs/geo_adv/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/20020006/.conda/envs/geo_adv/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/20020006/.conda/envs/geo_adv/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/20020006/.conda/envs/geo_adv/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/20020006/.conda/envs/geo_adv/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/20020006/.conda/envs/geo_adv/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/20020006/.conda/envs/geo_adv/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/20020006/.conda/envs/geo_adv/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/20020006/.conda/envs/geo_adv/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/20020006/.conda/envs/geo_adv/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/20020006/.conda/envs/geo_adv/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/20020006/.conda/envs/geo_adv/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/20020006/.conda/envs/geo_adv/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/20020006/.conda/envs/geo_adv/lib/python3.6/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/20020006/.conda/envs/geo_adv/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/20020006/.conda/envs/geo_adv/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/20020006/.conda/envs/geo_adv/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/20020006/.conda/envs/geo_adv/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/20020006/.conda/envs/geo_adv/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 649, in build_extensions
    build_ext.build_extensions(self)
  File "/home/20020006/.conda/envs/geo_adv/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/20020006/.conda/envs/geo_adv/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/20020006/.conda/envs/geo_adv/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/20020006/.conda/envs/geo_adv/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/20020006/.conda/envs/geo_adv/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 478, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/20020006/.conda/envs/geo_adv/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/20020006/.conda/envs/geo_adv/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1529, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

**Comment by itailang** [comment]
Dear @binbbaz,

Thank you for your interest in our project. I suggest that you run the commands in the file [compile_op_pt.sh](https://github.com/itailang/geometric_adv/blob/master/compile_op_pt.sh) in a command line, and validate that the CUDA path and the other related paths are as you would like them to be. For example, use:
```bash
export CUDA_HOME=/usr/local/cuda-11.1
```

and then validate the path by:
```bash
echo $CUDA_HOME
```
(you should get `/usr/local/cuda-11.1`).

After the paths are set correctly, compile the op:
```
cd ./transfer/atlasnet/
python auxiliary/ChamferDistancePytorch/chamfer3D/setup.py install
```

**Comment by binbbaz** [comment]
Thank you. Though I got some warnings but it worked for me.

The command **bash runner_indices_for_attack.sh** seems to be taking too much time to run. 

Is it normal?

**Comment by itailang** [comment]
Glad to hear that!

Regarding the indices command, it should take some time since it computes the distance matrix between all point clouds in the test set. This matrix is used for selecting target candidates for the attack. 

Note that the script uses a loop over this command:
```bash
python prepare_indices_for_attack.py --ae_folder log/autoencoder_victim --get_chamfer_nn_idx 1 --pc_start_idx $i --pc_batch_size 100
```

You can run this command from the command line (say, with setting the pc_start_idx to 0) and see how much time it takes on your machine. Then, multiply this time period by the number of iterations in the loop to estimate the run time of the script.

**Comment by binbbaz** [comment]
@itailang 
Thank you for the information

100 iterations runs for two hours on my machine. I expect it to run for almost four days.

![index_1](https://user-images.githubusercontent.com/20611722/126583805-5fc68fc0-0641-4856-b930-445f333816b7.png)

**Comment by itailang** [comment]
Dear @binbbaz,
It seems that your computation does not run on a GPU. For reference, the run time of this computation on my GPU is about half a minute.

![snapshot](https://user-images.githubusercontent.com/36666820/126591345-dc84438e-f630-43ef-907a-39ad1ee6ed2c.png)

**Comment by binbbaz** [comment]
I'll check it out and get back to you. Thank you
